#include "VSTComponents.h"

#include "OwlDSP/CMultiChannelIir.cpp"
#include "OwlDSP/DSPDelay.cpp"
#include "OwlDSP/DSPIntegration.cpp"
#include "OwlDSP/DSPLowpassFilter2.cpp"

#include "Owl/AudioQueue.cpp"
#include "Owl/ProperiesRegistry.cpp"
#include "Owl/SynthState.cpp"
#include "Owl/Toolbox.cpp"
#include "Owl/VoiceModuleBase.cpp"
#include "Owl/VoiceModuleHost.cpp"
#include "Owl/SynthStateManager.cpp"

#include "PresetBrowser/PresetBrowser.cpp"
#include "PresetBrowser/PresetBrowserImpl.cpp"
#include "PresetBrowser/PresetItemAdapter.cpp"

#include "OwlVoices/ControlVoltageSource.cpp"
#include "OwlVoices/DelayVoice.cpp"
#include "OwlVoices/EnvelopeVoice.cpp"
#include "OwlVoices/FilterVoice.cpp"
#include "OwlVoices/LfoOscillatorVoice.cpp"
#include "OwlVoices/LimiterVoice.cpp"
#include "OwlVoices/MixerVoice.cpp"
#include "OwlVoices/MultiModeOscillator.cpp"
#include "OwlVoices/NoiseVoice.cpp"
#include "OwlVoices/SawtoothVoice.cpp"